apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://194.177.207.38:8086
    basicAuth: true
    basicAuthUser: team19
    basicAuthPassword: ***REMOVED***
    jsonData:
      version: Flux
      organization: team19
      defaultBucket: team19_db
    secureJsonData: {}
    isDefault: true
